apiVersion: v1
kind: Pod
metadata: 
  name: refering  ConfigMap
  labels:
    purpose: practice
  spec:
    containers:
    - name: nginx
      image: nginx
      envFrom:
        - configMapRef:
            name: DemoMapfile