apiVersion: v1
kind: Pod
metadata: 
  name: referingconfigmap
  labels:
    purpose: practice
spec:
  containers:
  - name: nginx
    image: nginx  
    envFrom:
      - configMapRef:
          name: demomapfile